name: Deploy Shiny App

on:
  push:
    branches:
      - master  # Runs on push to master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libgsl-dev

      - name: Install R and dependencies
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'  # Use latest stable R version

      - name: Install required R packages
        run: |
          install.packages(
            c(
              "shiny", "dplyr", "ggplot2", "scales", "tidyr", "readr",
              "forecast", "prophet", "modeltime", "tidymodels", "timetk",
              "lubridate", "timeDate", "gridExtra", "mgcv", "plotly", "DT",
              "openai", "memoise", "imputeTS", "zoo", "shinyjs",
              "shinycssloaders", "shinyWidgets", "rsconnect"
            ), 
            dependencies=TRUE, repos="http://cran.r-project.org"
          )
        shell: Rscript {0}

      - name: Verify installed packages
        run: |
          installed <- installed.packages()[,1]
          print(installed)
        shell: Rscript {0}

      - name: Deploy to ShinyApps.io
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          library(rsconnect)

          rsconnect::setAccountInfo(
            name = Sys.getenv("SHINYAPPS_ACCOUNT"),
            token = Sys.getenv("SHINYAPPS_TOKEN"),
            secret = Sys.getenv("SHINYAPPS_SECRET")
          )
          
          rsconnect::deployApp(
            appName = "forecast-booking-curve"
          )
        shell: Rscript {0}
