name: Deploy Shiny App

on:
  push:
    branches:
      - master  # Run this workflow when changes are pushed to master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # ✅ Install system dependencies (Fixes libcurl error)
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev

    - name: Install R and dependencies
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.0'  # Use latest stable R version

    - name: Install required R packages
      run: |
        install.packages("rsconnect")
        install.packages("shiny")
        install.packages("tidyverse")   # Covers dplyr, ggplot2, tidyr, readr, lubridate
        install.packages("plotly")
        install.packages("DT")
        
        # ✅ Install forecasting & modeling packages
        install.packages("forecast")
        install.packages("prophet")
        install.packages("modeltime")
        install.packages("tidymodels")
        install.packages("timetk")

        # ✅ Install additional dependencies
        install.packages("scales")
        install.packages("timeDate")
        install.packages("gridExtra")
        install.packages("mgcv")
      shell: Rscript {0}

    - name: Deploy to ShinyApps.io
      env:
        SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: |
        library(rsconnect)
        rsconnect::setAccountInfo(
          name = Sys.getenv("SHINYAPPS_ACCOUNT"),
          token = Sys.getenv("SHINYAPPS_TOKEN"),
          secret = Sys.getenv("SHINYAPPS_SECRET")
        )
        rsconnect::deployApp()
      shell: Rscript {0}
