name: Deploy Shiny App

on:
  push:
    branches:
      - master  # Runs on push to master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R and dependencies
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'  # Use latest stable R version

      - name: Install devtools
        run: |
          install.packages("devtools")
        shell: Rscript {0}

      - name: Install required R packages
        run: |
          list_of_packages <- c(
              "shiny", "dplyr", "ggplot2", "scales", "tidyr", "readr",
              "forecast", "prophet", "modeltime", "tidymodels", "timetk",
              "lubridate", "timeDate", "gridExtra", "mgcv", "plotly", "DT",
              "openai", "memoise", "imputeTS", "zoo", "shinyjs",
              "shinycssloaders", "shinyWidgets"
              )
              
          install.packages(list_of_packages)
          
        shell: Rscript {0}

      - name: Verify installed packages
        run: |
          installed <- installed.packages()[,1]
          print(installed)
        shell: Rscript {0}

      - name: Deploy to ShinyApps.io
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          list_of_packages <- c(
              "rsconnect", "shiny", "dplyr", "ggplot2", "scales", "tidyr", "readr",
              "forecast", "prophet", "modeltime", "tidymodels", "timetk",
              "lubridate", "timeDate", "gridExtra", "mgcv", "plotly", "DT",
              "openai", "memoise", "imputeTS", "zoo", "shinyjs",
              "shinycssloaders", "shinyWidgets"
              )
              
          install.packages(list_of_packages)
          
          library(rsconnect)
          library(shiny)
          library(dplyr)
          library(ggplot2)
          library(scales)
          library(tidyr)
          library(readr)
          library(forecast)
          library(prophet)
          library(modeltime)
          library(tidymodels)
          library(timetk)
          library(lubridate)
          library(timeDate)
          library(gridExtra)
          library(mgcv)
          library(plotly)
          library(DT)
          library(openai)
          library(memoise)
          library(imputeTS)
          library(zoo)
          library(shinyjs)
          library(shinycssloaders)
          library(shinyWidgets)
          
          rsconnect::setAccountInfo(
            name = Sys.getenv("SHINYAPPS_ACCOUNT"),
            token = Sys.getenv("SHINYAPPS_TOKEN"),
            secret = Sys.getenv("SHINYAPPS_SECRET")
          )
          
          rsconnect::deployApp(
            appName = "forecast-booking-curve"
          )
        shell: Rscript {0}
